project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/claire-hsieh
      - icon: linkedin
        href: https://www.linkedin.com/in/claire-hsieh-539456174/
format:
  html:
    theme: pulse
    css: styles.css

editor: visual

