project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - href: about.qmd
      - text: "Daily Entries"
        href: "random_thoughts/"
      - icon: github
        href: https://github.com/claire-hsieh
      - icon: linkedin
        href: https://www.linkedin.com/in/claire-hsieh-539456174/
  google-analytics: "G-C03LB9NEHL"
format:
  html:
    theme: 
      light: pulse
      dark: darkly
    css: styles.css

editor: visual

