---
title: "Reviewing dnf books"
date: "2024-1-18"
image: ""
categories: [books]
toc: true

comments:
  utterances:
    repo: claire-hsieh/blog
---

My own policy is to never finish a book I don't enjoy. Life is short enough, why waste it on something that you know isn't bringing you joy or fulfillment? But if you don't finish the book, are you qualified to review it? My opinion is yes, if you've finished a chapter or two. Where this threshold is, could be an interesting idea to quantify.

When reviewing a book, there are certain qualities to consider: writing, plot, characters, world-building, and some ineffable quality that ties it all together, which I'm just going to call pizzazz. Writing quality could most definitely be judged by the first few pages. The rest is a harder to say. Characters, I believe can

What about books that redeem themselves towards the end? This is a bit like a failing student redeeming their grade through the final exam. Would it be unfair to the writer if you don't finish the book and judge them solely through the first few chapters?

on one hand, it's a bit like judging someone after knowing them for five min.
